const wordsArr = [
    {word: "Bad", article: "das"},
    {word: "Küche", article: "die"},
    {word: "Floor", article: "der"},
    {word: "Kartoffel", article: "die"},
    {word: "Käse", article: "der"},
    {word: "Buch", article: "das"},
    {word: "Apfel", article: "der"},
    {word: "Sofa", article: "das"},
    {word: "Vase", article: "die"},
    {word: "Vogel", article: "der"},
    {word: "Hund", article: "das"},
    {word: "Maus", article: "die"},
    {word: "Regenschirm", article: "der"},
    {word: "Kind", article: "das"},
    {word: "Flasche", article: "die"},
    {word: "Zug", article: "der"},
    {word: "Bild", article: "das"},
    {word: "Musik", article: "die"},
    {word: "Hut", article: "der"},
    {word: "Auto", article: "das"},
    {word: "Tasse", article: "die"},
    {word: "Tisch", article: "der"},
    {word: "Haus", article: "das"},
    {word: "Katze", article: "die"},
    {word: "Stuhl", article: "der"},
    {word: "Fenster", article: "das"},
    {word: "Tür", article: "die"},
    {word: "Baum", article: "der"},
    {word: "Auto", article: "das"},
    {word: "die Lampe", article: "die"},
    {word: "Computer", article: "der"},
    {word: "Telefon", article: "das"},
    {word: "Uhr", article: "die"},
    {word: "Rose", article: "die"},
    {word: "Kugelschreiber", article: "der"}]

module.export = [wordsArr]